### ISSUE TITLE
Wrong order on x-axis?

### ISSUE THREAD

**Issue by Ser-Gen** [kinday/postcss-axis#1]
Usually, `right` is specified before `left` in shortland.

But we have just the opposite.
Input:
```css
.elem {
  margin-x: 10px 11px;
}
```

Output:
```css
.elem {
  margin-left: 10px;
  margin-right: 11px;
}
```

**Comment by kinday** [comment]
I noticed the word “usually”. Are you referring to TRBL model where right goes first? If not, could you provide any examples?

**Comment by Ser-Gen** [comment]
Yes, reffering to trbl. It's so habitually.

**Comment by kinday** [comment]
I can’t remember a case when shorthand has only left and right values. You may find it opinionated but I will leave it as is. No breaking changes today.

**Comment by Ser-Gen** [comment]
CSS has broke my mind :\
That's why I use `top` before `bottom`, `left` only after `right`, and there are mixins (`margin-x/y`, `padding-x/y`) in my legacy code with this logic within.
Could you provide option to change order?

**Comment by kinday** [comment]
Yep, this approach is suitable to me.

**Comment by kinday** [comment]
Here you go!

**Comment by Ser-Gen** [comment]
Great, thank you!

**Comment by Ser-Gen** [comment]
Oops, right now `top` and `bottom` are also swaps with `trbl: true` :\

```pcss
.rl {
	margin-x: 10px 20px;
}
.tb {
	margin-y: 10px 20px;
}
```

```css
.rl {
	margin-left: 20px;
	margin-right: 10px;
}
.tb {
	margin-top: 20px;
	margin-bottom: 10px;
}
```
