### ISSUE TITLE
Bug in shortland border

### ISSUE THREAD

**Issue by Ser-Gen** [kinday/postcss-axis#2]
Input:
```css
.elem {
  border-x: 1px solid #f00;
}
```

Output:
```css
.elem {
  border-left: 1px;
  border-right: solid;
}
```
